package ie.atu.sw;

public class UserInputtedData {

    private int nGramSize; //Size of nGram window

    private String textDirectory; //Directory location of text files to be parsed

    private String outputFilename;
    private boolean isWindowSliding; //If TRUE - nGrams are generated by incrementing 1 character at a time. If FALSE - then nGrams are generated by incrementing by the nGram size
    public int getNGramSize() {
        return nGramSize;
    }
    public void setNGramSize(int nGramSize) {
        this.nGramSize = nGramSize;
    }

    public String getDirectory() {
        return textDirectory;
    }

    public void setDirectory(String textDirectory) {
        this.textDirectory = textDirectory;
    }

    public String getOutputFilename() {
        return outputFilename;
    }

    public void setOutputFilename(String outputFilename) {
        this.outputFilename = outputFilename;
    }

    public void setIsWindowSliding(boolean isWindowSliding) {
        this.isWindowSliding = isWindowSliding;
    }

    public boolean getIsWindowSliding() {
        return isWindowSliding;
    }
}
