package ie.atu.sw;

/*
    Class UserInputtedData is used to store the user inputted parameters to run the program
    int nGramSize
    String textDirectory - directory in which the texts are stored
    String outputFilename
    boolean isWindowSliding

    Contains getters and setters for all these fields
 */
public class UserInputtedData {

    private int nGramSize; //Size of nGram window
    private String textDirectory; //Directory location of text files to be parsed
    private String outputFilename;
    private boolean isWindowSliding; //If TRUE - nGrams are generated by incrementing 1 character at a time. If FALSE - then nGrams are generated by incrementing by the nGram size
    public int getNGramSize() {
        return nGramSize;
    }
    public void setNGramSize(int nGramSize) {
        // If user enters 0 as nGramSize change to 1 so program doesnt explode
        if (nGramSize == 0) {
            nGramSize = 1;
        }
        // Using Math.abs() to allow for -ve values being entered
        this.nGramSize = Math.abs(nGramSize);
    }

    public String getDirectory() {
        return textDirectory;
    }

    public void setDirectory(String textDirectory) {
        this.textDirectory = textDirectory;
    }

    public String getOutputFilename() {
        return outputFilename;
    }

    public void setOutputFilename(String outputFilename) {
        this.outputFilename = outputFilename;
    }

    public void setIsWindowSliding(boolean isWindowSliding) {
        this.isWindowSliding = isWindowSliding;
    }

    public boolean getIsWindowSliding() {
        return isWindowSliding;
    }
}
